# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestPE1601REGISTER():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_pE1601REGISTER(self):
        self.driver.get("http://127.0.0.1:5000/")
        self.driver.set_window_size(1382, 744)
        self.driver.find_element(By.LINK_TEXT, "Sign In").click()
        self.driver.find_element(By.LINK_TEXT, "Register here").click()
        self.driver.find_element(By.NAME, "email").send_keys(
            "emailtest@email.com")
        self.driver.find_element(By.ID, "password").send_keys("Passtest1!")
        self.driver.find_element(By.ID, "cpassword").send_keys("Passtest1!")
        self.driver.find_element(By.NAME, "firstName").send_keys("Test")
        self.driver.find_element(By.NAME, "lastName").send_keys("Name")
        self.driver.find_element(
            By.NAME, "address1").send_keys("Test Address 123")
        self.driver.find_element(By.NAME, "zipcode").send_keys("31273")
        self.driver.find_element(By.NAME, "city").send_keys("Miami")
        self.driver.find_element(By.NAME, "state").send_keys("Florida")
        self.driver.find_element(By.NAME, "country").send_keys("United States")
        self.driver.find_element(By.NAME, "phone").send_keys("+1 428 384 2832")
        self.driver.find_element(
            By.CSS_SELECTOR, "p:nth-child(13) > input").click()
        textResult = self.driver.find_element(By.XPATH, "/html/body/p").text
        assert textResult == "Registered Successfully"
